version: 1.0.{build}
image: Visual Studio 2022
environment:
  nodejs_version: '20'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - npm run build
test_script:
  - npm test
artifacts:
  - path: ./dist
after_build:
  - ps: |
      git config --global user.email "your-email@example.com"
      git config --global user.name "Your Name"
      git clone --branch=gh-pages https://$env:GITHUB_TOKEN@github.com/your-username/your-repository.git deploy
      robocopy .\dist\ deploy /MIR
      Push-Location deploy
      git add .
      git commit -m "Appveyor deploy [skip ci]" || exit 0
      git push origin gh-pages