version: 1.0.{build}
image: Ubuntu
environment:
  nodejs_version: '20'
install:
  - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm ci
build_script:
  - npm run build
test_script:
  - npm test
artifacts:
  - path: ./dist
