version: 1.0.{build}
image: Visual Studio 2022
environment:
  nodejs_version: '20'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - npm run build
test_script:
  - npm test
artifacts:
  - path: ./dist
after_build:
  - ps: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      git clone https://$env:GITHUB_TOKEN@github.com/waanh/dom.git repo
      robocopy .\dist\ repo /MIR
      Push-Location repo
      git add .
      if ((git commit -m "Appveyor deploy [skip ci]").ExitCode -ne 0) {
        Write-Host "Nothing to commit, skipping."
      }
      git push origin main