version: 1.0.{build}
image: Visual Studio 2022
environment:
  nodejs_version: '20'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - npm run build
test_script:
  - npm test
deploy:
  provider: GitHubPages
  token: "$(GITHUB_TOKEN)"
  force_update: true
  artifact: dist
  on:
    branch: main